### ISSUE TITLE
Custom provider with vhost address style does not work

### ISSUE THREAD

**Issue by sa7mon** [sa7mon/S3Scanner#242]
**Steps to reproduce**

1. Spin up the `dev mitm` docker compose profile
2. Edit `config.yml` to be:

```yaml
providers:
  custom:
    insecure: true
    endpoint_format: "https://$REGION.linodeobjects.com"
    regions:
      - "fr-par-1"
    address_style: "vhost"
```
3. Scan any single bucket: `go run main.go -provider custom -bucket google.com`
4. Observe the requests listed in mitmproxy are being sent to `https://fr-par-1.linodeobjects.com` instead of `https://google.com.fr-par-1.linodeobjects.com`
